facts:
  description: >
    Extract the facts expressed in the text. Facts are explicit assertions about the real world at the time of the content. Ex: the author is from a country called Canada.
    ### Text:
    {text}
    ### Context:
    {context}
  expected_output: >
    A bullet list of facts.

fact_assumptions:
  description: >
    Extract the fact assumptions expressed in the below text. Fact assumptions are necessary for facts to be true. These are generally boring and not useful. Ex: there exists a country called Canada. Regions of the world can be divided into countries.
    ### Text:
    {text}
    ### Context:
    {context}
  expected_output: >
    A bulletlist of fact assumptions.

first_order_beliefs:
  description: >
    Extract the first-order beliefs expressed in the below text. First-order beliefs are propositions immediately derivative from the content, without intermediary beliefs.
    ### Text:
    {text}
    ### Context:
    {context}
  expected_output: >
    A bullet list of first-order beliefs.

next_order_beliefs:
  description: >
    Extract the next-order beliefs expressed in the below text. Next-order beliefs are propositions that the first-order or other next-order beliefs depend upon to be true. Each layer of next-order beliefs are derived from the one previous layer and not layers beyond it. Don't describe the dependencies in the belief descriptions.
    ### Text:
    {text}
    ### Context:
    {context}
  expected_output: >
    A bullet list of next-order beliefs.

write_parable:
  description: >
    The following belief was derived from the text: {belief}
    Tell a parable that challenges the belief to be {action}.
    In the parable, make use of the characters, entities, events, setting, tone, and style of the text / context below.

    ### Text:
    {text}
    ### Context:
    {context}

  expected_output: >
    A parable that challenges the target belief to be {action}.
