name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      backend_image: ${{ steps.build_backend.outputs.image }}
      frontend_image: ${{ steps.build_frontend.outputs.image }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Backend Docker Image
        id: build_backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.BACKEND_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build and Push Frontend Docker Image
        id: build_frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.FRONTEND_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  test-frontend:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
          
      - name: Run frontend tests
        run: |
          docker run --rm ${{ needs.build.outputs.frontend_image }} npm test

  test-backend:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
          
      - name: Run backend tests
        run: |
          docker run --rm ${{ needs.build.outputs.backend_image }} python manage.py test

  deploy:
    needs: [test-frontend, test-backend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          TF_VAR_crewai_api_key: ${{ secrets.CREWAI_API_KEY }}
        run: terraform apply -auto-approve

      # Build and push Docker images to ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push frontend image to ECR
        run: |
          docker build -t ${{ steps.frontend_image.outputs.image }} ./frontend
          docker push ${{ steps.frontend_image.outputs.image }}
        env:
          ECR_REPOSITORY: ${{ steps.terraform-output.outputs.frontend_ecr_repository_url }}

      - name: Build, tag, and push backend image to ECR
        run: |
          docker build -t ${{ steps.backend_image.outputs.image }} ./backend
          docker push ${{ steps.backend_image.outputs.image }}
        env:
          ECR_REPOSITORY: ${{ steps.terraform-output.outputs.backend_ecr_repository_url }}

      # Add a step to capture terraform outputs
      - name: Get Terraform outputs
        id: terraform-output
        working-directory: ./terraform
        run: |
          echo "frontend_ecr_repository_url=$(terraform output -raw frontend_ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "backend_ecr_repository_url=$(terraform output -raw backend_ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "ecs_cluster_name=$(terraform output -raw ecs_cluster_name)" >> $GITHUB_OUTPUT
          echo "frontend_service_name=$(terraform output -raw frontend_service_name)" >> $GITHUB_OUTPUT
          echo "backend_service_name=$(terraform output -raw backend_service_name)" >> $GITHUB_OUTPUT

      # Update ECS services using the captured outputs
      - name: Update ECS services
        run: |
          aws ecs update-service --cluster ${{ steps.terraform-output.outputs.ecs_cluster_name }} --service ${{ steps.terraform-output.outputs.frontend_service_name }} --force-new-deployment
          aws ecs update-service --cluster ${{ steps.terraform-output.outputs.ecs_cluster_name }} --service ${{ steps.terraform-output.outputs.backend_service_name }} --force-new-deployment
