name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      backend_image: ${{ steps.build_backend.outputs.image }}
      frontend_image: ${{ steps.build_frontend.outputs.image }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Backend Docker Image
        id: build_backend
        run: |
          BACKEND_IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ secrets.BACKEND_ECR_REPOSITORY }}:${{ github.sha }}
          echo "BACKEND_IMAGE=$BACKEND_IMAGE" >> $GITHUB_ENV
          cd backend
          docker build -t $BACKEND_IMAGE .

      - name: Run backend tests
        run: |
          docker run --rm ${{ env.BACKEND_IMAGE }} uv run python manage.py test
      
      - name: Build Frontend Docker Image
        id: build_frontend
        run: |
          FRONTEND_IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ secrets.FRONTEND_ECR_REPOSITORY }}:${{ github.sha }}
          echo "FRONTEND_IMAGE=$FRONTEND_IMAGE" >> $GITHUB_ENV
          cd frontend
          docker build -t $FRONTEND_IMAGE .

      - name: Run frontend tests
        run: |
          docker run --rm ${{ env.FRONTEND_IMAGE }} npm test -- --watchAll=false

      - name: Push Backend Docker Image
        run: |
          docker push ${{ env.BACKEND_IMAGE }}

      - name: Push Frontend Docker Image
        run: |
          docker push ${{ env.FRONTEND_IMAGE }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        env:
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          TF_VAR_crewai_api_key: ${{ secrets.CREWAI_API_KEY }}
        run: terraform plan -lock=false

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          TF_VAR_crewai_api_key: ${{ secrets.CREWAI_API_KEY }}
        run: terraform apply -auto-approve

      # Build and push Docker images to ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Add a step to capture terraform outputs
      - name: Get Terraform outputs and update ECS services
        id: terraform-output
        working-directory: ./terraform
        run: |
          # Function to extract the actual output value
          extract_value() {
            echo "$1" | grep -oP '(?<=stdout: ).*(?= ::debug::)'
          }

          # Capture the raw output and extract the actual value
          RAW_ECS_CLUSTER_NAME=$(terraform output -raw ecs_cluster_name 2>/dev/null || echo "Error capturing ecs_cluster_name")
          ECS_CLUSTER_NAME=$(extract_value "$RAW_ECS_CLUSTER_NAME")

          RAW_FRONTEND_SERVICE_NAME=$(terraform output -raw frontend_service_name 2>/dev/null || echo "Error capturing frontend_service_name")
          FRONTEND_SERVICE_NAME=$(extract_value "$RAW_FRONTEND_SERVICE_NAME")

          RAW_BACKEND_SERVICE_NAME=$(terraform output -raw backend_service_name 2>/dev/null || echo "Error capturing backend_service_name")
          BACKEND_SERVICE_NAME=$(extract_value "$RAW_BACKEND_SERVICE_NAME")

          # Ensure no errors are written to the output
          if [[ $ECS_CLUSTER_NAME == Error* || $FRONTEND_SERVICE_NAME == Error* || $BACKEND_SERVICE_NAME == Error* ]]; then
            echo "Error: One or more Terraform outputs could not be captured."
            exit 1
          fi

          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $FRONTEND_SERVICE_NAME --force-new-deployment
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $BACKEND_SERVICE_NAME --force-new-deployment
